### ISSUE TITLE
1.17 unexpected behavior

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [foncused/LongerDays#1]
The plugin behaves very strangely on 1.17 in any situation. The phase of the moon changes every second at night, the clouds move in huge "jumps".

**Comment by Envel-Nikita-Gutsenkov** [comment]
gif https://imgur.com/ujVqnGX

**Comment by foncused** [comment]
Does this occur on the default graphics? That looks like a resource pack.
Output of `/version` please.

**Comment by Envel-Nikita-Gutsenkov** [comment]
spigot/paper/tuinity/purpur 1.17.1

I'm showing an example with a resource package as a more visual option. it's the same with default resources, but it's less noticeable. with a default  resource package, you can clearly see how the moon changes its phase dozens of times per second.

**Comment by foncused** [comment]
I will have to take a more thorough look and try to reproduce the issue so I can fix it. Thanks for the info.

**Comment by Envel-Nikita-Gutsenkov** [comment]
just start the 1.17 server and you will have this problem)

**Comment by vilhalmer** [comment]
I also noticed that the F3 day count increases _extremely_ rapidly and the local difficulty is recalculated much more frequently than normal. These are probably related, some sort of tick speed issue.

**Comment by foncused** [comment]
Should be fixed in 1.0.4, available on Spigot forum. https://www.spigotmc.org/resources/longerdays.80610/

**Comment by foncused** [comment]
Just for purposes of documentation, this was *actually* fixed in v1.0.5, available on Spigot.
