### ISSUE TITLE
Sets time to night on sleep.

### ISSUE THREAD

**Issue by Hexidecimark** [foncused/LongerDays#2]
Days and nights set to 60m each.

Using Spigot for 1.18.2

Running:
worldedit-bukkit-7.2.10.jar
worldguard-bukkit-7.0.7-dist.jar
LongerDays.jar
towny-0.98.1.9.jar
SkinsRestorer.jar
LuckPerms-Bukkit-5.4.9.jar
EssentialsXDiscord-2.20.0-dev+5-d891268.jar
EssentialsX-2.20.0-dev+5-d891268.jar
EssentialsXChat-2.20.0-dev+5-d891268.jar
EssentialsXSpawn-2.20.0-dev+5-d891268.jar

**Comment by foncused** [comment]
Resolved in version 1.0.6 of the plugin, available on Spigot.
